const glow=document.querySelector('.cursor-glow');
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduced&&glow){window.addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'});}
const demos={
 code:{mode:'CODE / ARCHITECT',title:'Build a landing page that feels expensive.',html:'<p>Start by removing everything that looks like a template.</p><div class="code-art"><span>01</span><code>define the visual language</code><span>02</span><code>make hierarchy unavoidable</code><span>03</span><code>animate only what matters</code><span>04</span><code>ship the thing</code></div><p class="answer-last">The result should not announce that it was built by AI. It should make people wonder who built it.</p>'},
 strategy:{mode:'STRATEGY / ADVERSARY',title:'Find the hidden weakness in my plan.',html:'<p>Do not start by improving it. Start by trying to break it.</p><div class="strategy-list"><div><b>01</b><span>ASSUMPTION</span><strong>What must be true for this to work?</strong></div><div><b>02</b><span>BOTTLENECK</span><strong>Where does the plan fail at scale?</strong></div><div><b>03</b><span>BLIND SPOT</span><strong>What evidence would change the decision?</strong></div></div><p class="answer-last">A useful collaborator is not the one who agrees fastest. It is the one who finds the expensive mistake before you make it.</p>'},
 creative:{mode:'CREATIVE / DIRECTOR',title:'Take this vague idea and make it unforgettable.',html:'<p>First, give the idea a point of view.</p><div class="creative-board"><div><span>MOOD</span><b>quiet confidence</b></div><div><span>RULE</span><b>one unforgettable gesture</b></div><div><span>VOICE</span><b>precise, never loud</b></div><div><span>IMAGE</span><b>light moving through glass</b></div></div><p class="answer-last">Then remove everything that does not reinforce the idea. Distinctiveness is usually subtraction wearing better clothes.</p>'},
 science:{mode:'SCIENCE / TRANSLATOR',title:'Explain something impossible without dumbing it down.',html:'<p>Keep the real mechanism. Change the mental model.</p><div class="science-flow"><span>COMPLEX SYSTEM</span><b>→</b><span>MENTAL MODEL</span><b>→</b><span>INTUITION</span></div><p>Quantum behavior, neural networks, relativity, cryptography. The goal is not to replace the mathematics. It is to give the mathematics somewhere useful to land.</p><p class="answer-last">Clarity is not simplification. It is compression without losing the signal.</p>'}
};
document.querySelectorAll('.prompt').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.prompt').forEach(x=>x.classList.remove('active'));button.classList.add('active');const d=demos[button.dataset.demo];const body=document.querySelector('.answer-body');body.classList.add('changing');setTimeout(()=>{document.querySelector('#answerMode').textContent=d.mode;document.querySelector('#answerTitle').textContent=d.title;document.querySelector('#answerContent').innerHTML=d.html;body.classList.remove('changing')},reduced?0:220)}));
async function startCheckout(plan,button){button.disabled=true;button.textContent='Opening Stripe…';try{const r=await fetch('/api/create-checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({plan})});const data=await r.json();if(!r.ok||!data.url)throw new Error(data.error||'Could not start checkout');window.location.href=data.url}catch(e){button.disabled=false;button.textContent='Try again ↗';alert(e.message)}}
document.querySelectorAll('[data-buy]').forEach(button=>button.addEventListener('click',e=>{e.preventDefault();startCheckout(button.dataset.buy,button)}));
document.querySelectorAll('.rival').forEach(r=>r.addEventListener('click',()=>{document.querySelectorAll('.rival').forEach(x=>x.classList.remove('active'));r.classList.add('active')}));
const reveal=[...document.querySelectorAll('.capability-grid article,.rival,.manifesto-grid,.demo-stage,.finale h2')];
if(!reduced&&'IntersectionObserver'in window){reveal.forEach(x=>{x.style.opacity='0';x.style.transform='translateY(20px)';x.style.transition='opacity .7s ease,transform .7s ease'});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.style.opacity='1';e.target.style.transform='translateY(0)';io.unobserve(e.target)}}),{threshold:.12});reveal.forEach(x=>io.observe(x))}
